// <auto-generated />
namespace ngshowcase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Item_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Item_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201405311655282_Item_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
